export default {
  "content": [
    "article",
    [
      "h1",
      "Upload"
    ],
    [
      "p",
      "用于文件上传"
    ],
    [
      "h2",
      "代码演示"
    ],
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "属性"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "accept"
          ],
          [
            "td",
            "接受文件上传的类型"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "无"
          ]
        ],
        [
          "tr",
          [
            "td",
            "beforeUpload"
          ],
          [
            "td",
            "文件上传前的钩子，参数为上传的文件列表，若返回false，则不上传所选文件"
          ],
          [
            "td",
            "function(file)"
          ],
          [
            "td",
            "无"
          ]
        ],
        [
          "tr",
          [
            "td",
            "children"
          ],
          [
            "td",
            "Upload默认不包含任何内容，你需要在其中包裹一个元素，作为点击目标"
          ],
          [
            "td",
            "element"
          ],
          [
            "td",
            "无"
          ]
        ],
        [
          "tr",
          [
            "td",
            "disabled"
          ],
          [
            "td",
            "禁用上传"
          ],
          [
            "td",
            "bool"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "multiple"
          ],
          [
            "td",
            "支持多文件上传"
          ],
          [
            "td",
            "bool"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "文件上传回调，参数为上传的文件列表"
          ],
          [
            "td",
            "function(file)"
          ],
          [
            "td",
            "无"
          ]
        ]
      ]
    ],
    [
      "h2",
      "提示"
    ],
    [
      "p",
      "如果你想对上传文件数量或者上传文件大小做限制，可以在beforeUpload中加入你自己的判断逻辑"
    ]
  ],
  "meta": {}
}